/* Test the live report's source of truth without a browser or GIS runtime. */
const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const path=require("node:path");
const root=path.join(__dirname,"..");
const context={window:{}};
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(root,"docs/live-report-model.js"),"utf8"),context);
const model=context.window.LiveReportModel;
const history=JSON.parse(fs.readFileSync(path.join(root,"docs/data/analysis_history.json"),"utf8"));
const images=JSON.parse(fs.readFileSync(path.join(root,"docs/data/satellite_part_1.json"),"utf8"));
const dates=images.filter(x=>x.plot==="13-STC").map(x=>x.date);
const one=model.make(history.plots["13-STC"],dates);
assert.equal(one.latestDate,"2026-10-07","Scene date should be the latest actual satellite image");
assert.equal(one.current.date,"2026-09-29","Partial scene must not replace Current");
assert.equal(one.latestRecord.analysis_status,"PARTIAL");
assert.equal(one.latestRecord.valid_pct,44.7);
assert.equal(one.latestRecord.observed_water_rai,44.5);
assert.equal(one.current.water_pct,88.1);
assert.equal(one.previous.date,"2026-04-30");
assert.ok(one.pending,"Partial scene should produce a visible warning");
assert.ok(Math.abs(one.deltaWater-194.92)<1e-6);
assert.equal(one.newWater,194.91,"Net water change must not be mislabeled new-water area");
const newScene={date:"2026-10-09",analysis_status:"AUTO_VALID",valid_pct:91,water_rai:180,water_pct:69.25,ndvi:0.43,new_water_rai:null};
const updated=model.make([...history.plots["13-STC"],newScene],[...dates,"2026-10-09"]);
assert.equal(updated.current.date,"2026-10-09","New valid scenes must replace Current without editing plots.json");
assert.equal(updated.previous.date,"2026-09-29");
assert.equal(updated.newWater,null,"Unknown new-water mask must not be invented");
assert.ok(Math.abs(updated.deltaWater+49.73)<1e-6);
assert.equal(updated.pending,false);
const future=model.make([...history.plots["13-STC"],newScene],[...dates,"2026-10-09","2026-10-12"]);
assert.equal(future.latestRecord,null);
assert.equal(future.latestDate,"2026-10-12");
assert.equal(future.pending,true,"New image without analysis is pending");
const empty=model.make([],[ "2026-10-12" ]);
assert.equal(empty.current,null);
assert.equal(empty.pending,true);
console.log("LIVE REPORT TEST PASS — current QA, partial observation, new valid image, pending image, net-vs-new area");
